version: "3.8"
services:
  website:
    image: nginx:alpine
    container_name: website
    volumes:
      - ./:/usr/share/nginx/html:ro   # serve your repo files
    ports:
      - "8080:80"   # expose locally on 8080 (Caddy will front it)
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
